import { auth } from "@/auth";
import Navbar from "@/components/navbar/navbar";
import { TRPCProvider } from "@/components/trpc-context-provider";
import type { Metadata } from "next";
import { SessionProvider, useSession } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <TRPCProvider>{children}</TRPCProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
